(function(){"use strict";var H={};var esc=function(s){return String(s==null?"":s);};var KIND={macros:"macro",weakauras:"weakaura"};var LABEL={macro:"Macro",weakaura:"WeakAura"};var PLURAL={macro:"Macros",weakaura:"WeakAuras"};var API="/sidekick/api/community";var S={kind:"macro",items:[],total:0,loading:false,error:"",stale:false,f:{scope:"",cls:"",spec:"",category:"",q:"",sort:"top"},detail:null,detailLoading:false,voted:{},submitOpenedAt:0,editOpenedAt:0};var _searchTimer=null;function taxonomy(){var t=(window.ASC&&window.ASC.submissionTaxonomy)||{};return(t.categories&&t.categories[S.kind])||[];}
function catLabel(id){var hit=taxonomy().filter(function(c){return c.id===id;})[0];return hit?hit.label:id;}
function classes(){return(H.classes&&H.classes())||[];}
function specsOf(clsName){var c=classes().filter(function(x){return x.name===clsName;})[0];return c?(c.specs||[]).map(function(s){return s.n;}):[];}
function voteToken(){var k="ascCommunityToken";var t="";try{t=localStorage.getItem(k)||"";}catch(e){return"";}
if(t)return t;try{var buf=new Uint8Array(16);(window.crypto||{}).getRandomValues(buf);t=Array.prototype.map.call(buf,function(b){return("0"+b.toString(16)).slice(-2);}).join("");localStorage.setItem(k,t);}catch(e){return"";}
return t;}
function loadVoted(){try{S.voted=JSON.parse(localStorage.getItem("ascCommunityVoted")||"{}")||{};}
catch(e){S.voted={};}}
function saveVoted(){try{localStorage.setItem("ascCommunityVoted",JSON.stringify(S.voted));}catch(e){}}
function snapshotItems(){var snap=(window.ASC&&window.ASC.community)||{};return(snap.items||[]).filter(function(it){return it.kind===S.kind;});}
function applyLocalFilters(items){var f=S.f;var q=(f.q||"").toLowerCase();return items.filter(function(it){if(f.scope&&it.scope!==f.scope)return false;if(f.cls&&it.cls!==f.cls)return false;if(f.spec&&it.spec!==f.spec)return false;if(f.category&&it.category!==f.category)return false;if(q){var hay=(it.title+" "+it.description+" "+it.author).toLowerCase();if(hay.indexOf(q)===-1)return false;}
return true;}).sort(function(a,b){if(!!b.featured!==!!a.featured)return b.featured?1:-1;if(f.sort==="new")return(b.createdAt||"").localeCompare(a.createdAt||"");return(b.votes||0)-(a.votes||0);});}
function qs(obj){var out=[];for(var k in obj){if(obj[k]!==""&&obj[k]!=null)out.push(encodeURIComponent(k)+"="+encodeURIComponent(obj[k]));}
return out.length?"?"+out.join("&"):"";}
function targetText(it){if(it.scope==="general"||!it.cls)return"General";return it.spec?it.cls+" / "+it.spec:it.cls;}
function targetChip(it){if(it.scope==="general"||!it.cls)return"<span class='cx-chip'>General</span>";if(it.spec&&H.specRef)return H.specRef(it.cls,it.spec,{icon:true,current:true});if(H.classRef)return H.classRef(it.cls,{icon:true,current:true});return"<span class='cx-chip'>"+esc(targetText(it))+"</span>";}
function flagBadges(it){var out="";if((it.flags||[]).indexOf("custom_lua")!==-1||it.hasLua){out+="<span class='cx-flag cx-flag-warn' title='This import contains custom Lua that will run in your client. Review it before importing.'>Contains code</span>";}
if((it.flags||[]).indexOf("script")!==-1){out+="<span class='cx-flag'>Uses /run</span>";}
return out;}
function voteBtn(it){var on=!!S.voted[it.id];return"<button class='cx-vote"+(on?" on":"")+"' data-cx-vote='"+esc(it.id)+"' "+"aria-label='Upvote' aria-pressed='"+(on?"true":"false")+"'>"+"<span class='cx-vote-a'>&#9650;</span><span class='cx-vote-n'>"+esc(String(it.votes||0))+"</span></button>";}
function card(it){var body="";if(S.kind==="macro"){body="<pre class='macro-code cx-code'>"+esc(it.body||"")+"</pre>";}
return"<article class='cx-card"+(it.featured?" cx-pinned":"")+"'>"+"<div class='cx-card-h'>"+
voteBtn(it)+"<div class='cx-card-t'>"+"<a class='cx-title nava' href='"+esc(H.hrefFor({view:S.kind==="macro"?"macros":"weakauras",sub:it.id}))+"' data-cx-open='"+esc(it.id)+"'>"+esc(it.title)+"</a>"+"<div class='cx-meta'>"+
(it.featured?"<span class='cx-flag cx-flag-pin'>Pinned</span>":"")+
targetChip(it)+"<span class='cx-chip'>"+esc(catLabel(it.category))+"</span>"+
flagBadges(it)+
(it.author?"<span class='cx-by'>by "+esc(it.author)+"</span>":"")+"</div>"+"</div>"+"</div>"+"<p class='cx-desc'>"+esc(it.description)+"</p>"+
body+"<div class='cx-card-a'>"+"<button class='cx-copy' data-cx-copy='"+esc(it.id)+"'>Copy "+esc(S.kind==="macro"?"macro":"import string")+"</button>"+
(it.wagoUrl?"<a class='cx-link' href='"+esc(it.wagoUrl)+"' target='_blank' rel='noopener noreferrer'>Wago</a>":"")+"</div>"+"</article>";}
function filterBar(){var f=S.f;var scopeTabs=[["","All"],["general","General"],["class","Class"],["spec","Spec"]].map(function(o){return"<button class='cx-tab"+(f.scope===o[0]?" on":"")+"' data-cx-scope='"+esc(o[0])+"'>"+esc(o[1])+"</button>";}).join("");var clsOpts="<option value=''>Any class</option>"+classes().slice().sort(function(a,b){return a.name.localeCompare(b.name);}).map(function(c){return"<option value='"+esc(c.name)+"'"+(f.cls===c.name?" selected":"")+">"+esc(c.name)+"</option>";}).join("");var specOpts="<option value=''>Any spec</option>"+specsOf(f.cls).map(function(n){return"<option value='"+esc(n)+"'"+(f.spec===n?" selected":"")+">"+esc(n)+"</option>";}).join("");var cats="<button class='cx-chipbtn"+(f.category===""?" on":"")+"' data-cx-cat=''>All</button>"+
taxonomy().map(function(c){return"<button class='cx-chipbtn"+(f.category===c.id?" on":"")+"' data-cx-cat='"+esc(c.id)+"' title='"+esc(c.desc||"")+"'>"+esc(c.label)+"</button>";}).join("");return"<div class='cx-filters'>"+"<div class='cx-tabs'>"+scopeTabs+"</div>"+"<div class='cx-row'>"+"<select class='cx-sel' data-cx-cls aria-label='Filter by class'>"+clsOpts+"</select>"+"<select class='cx-sel' data-cx-spec aria-label='Filter by spec'"+(f.cls?"":" disabled")+">"+specOpts+"</select>"+"<input class='cx-search' data-cx-q value='"+esc(f.q)+"' placeholder='Search title, description or author' aria-label='Search'>"+"<select class='cx-sel cx-sort' data-cx-sort aria-label='Sort'>"+"<option value='top'"+(f.sort==="top"?" selected":"")+">Top rated</option>"+"<option value='new'"+(f.sort==="new"?" selected":"")+">Newest</option>"+"</select>"+"</div>"+"<div class='cx-chips'>"+cats+"</div>"+"</div>";}
function resultsHtml(){if(S.loading)return"<div class='cx-load'>Loading…</div>";var notice="";if(S.stale){notice="<div class='cx-notice'>Showing the bundled copy — live results are unavailable right now, so this may be out of date.</div>";}else if(S.error){notice="<div class='cx-notice cx-notice-bad'>"+esc(S.error)+"</div>";}
if(!S.items.length){return notice+"<div class='empty'><h2>Nothing here yet</h2><p>"+
(S.f.q||S.f.cls||S.f.category||S.f.scope?"No "+esc(PLURAL[S.kind].toLowerCase())+" match those filters. Try widening them.":"Be the first to submit one.")+"</p></div>";}
return notice+"<p class='cx-count muted small'>"+esc(String(S.total))+" "+
esc(S.total===1?LABEL[S.kind].toLowerCase():PLURAL[S.kind].toLowerCase())+"</p>"+"<div class='cx-list'>"+S.items.map(card).join("")+"</div>";}
function browseView(){var isMacro=S.kind==="macro";return"<section class='hero hero-sm'><div class='hero-glow'></div><div class='hero-in'>"+"<div class='hero-crumb'>Conquest of Azeroth</div>"+"<h1 class='hero-h'><span>"+esc(PLURAL[S.kind])+"</span></h1>"+"<p class='hero-p'>"+
(isMacro?"Player-submitted macros for every class and spec — copy one, or share yours.":"Player-submitted WeakAuras for Conquest of Azeroth — built for Ascension's own client, not retail.")+"</p>"+"<div class='hero-cta'><button class='cx-submit-cta' data-cx-gosubmit>Submit "+
esc(isMacro?"a macro":"a WeakAura")+"</button></div>"+"</div></section>"+
filterBar()+"<div id='cx-results'>"+resultsHtml()+"</div>";}
function detailView(id){if(S.detailLoading)return"<div class='cx-load'>Loading…</div>";var it=S.detail;if(!it||it.id!==id){return"<div class='empty'><h2>Not found</h2><p>That entry may have been removed. "+"<button class='cx-inline-link' data-cx-goback>Back to "+esc(PLURAL[S.kind].toLowerCase())+"</button></p></div>";}
return"<section class='hero hero-sm'><div class='hero-glow'></div><div class='hero-in'>"+"<div class='hero-crumb'><button class='cx-inline-link' data-cx-goback>"+esc(PLURAL[S.kind])+"</button></div>"+"<h1 class='hero-h'><span>"+esc(it.title)+"</span></h1>"+"<p class='hero-p'>"+esc(it.description)+"</p>"+"</div></section>"+"<section class='sec'>"+"<div class='cx-detail-meta'>"+
voteBtn(it)+
targetChip(it)+"<span class='cx-chip'>"+esc(catLabel(it.category))+"</span>"+
flagBadges(it)+
(it.author?"<span class='cx-by'>by "+esc(it.author)+"</span>":"")+"</div>"+
((it.flags||[]).indexOf("custom_lua")!==-1||it.hasLua?"<div class='cx-warn'><b>This import contains custom code.</b> WeakAuras will run it in your client. "+"A maintainer reviewed it before it was published, but read it yourself if you are unsure — that is what the addon's own import warning is for.</div>":"")+"<pre class='macro-code cx-code cx-code-full'>"+esc(it.body||"")+"</pre>"+"<div class='cx-card-a'>"+"<button class='cx-copy cx-copy-lg' data-cx-copy='"+esc(it.id)+"'>Copy "+esc(S.kind==="macro"?"macro":"import string")+"</button>"+
(it.wagoUrl?"<a class='cx-link' href='"+esc(it.wagoUrl)+"' target='_blank' rel='noopener noreferrer'>View on Wago</a>":"")+"<button class='cx-link' data-cx-suggest='"+esc(it.id)+"'>Suggest an edit</button>"+"</div>"+"</section>";}
function submitView(){var isMacro=S.kind==="macro";var clsOpts="<option value=''>— pick a class —</option>"+classes().slice().sort(function(a,b){return a.name.localeCompare(b.name);}).map(function(c){return"<option value='"+esc(c.name)+"'>"+esc(c.name)+"</option>";}).join("");var catOpts=taxonomy().map(function(c){return"<option value='"+esc(c.id)+"'>"+esc(c.label)+"</option>";}).join("");return"<section class='hero hero-sm'><div class='hero-glow'></div><div class='hero-in'>"+"<div class='hero-crumb'><button class='cx-inline-link' data-cx-goback>"+esc(PLURAL[S.kind])+"</button></div>"+"<h1 class='hero-h'><span>Submit "+esc(isMacro?"a macro":"a WeakAura")+"</span></h1>"+"<p class='hero-p'>Shared with the community and credited to you. Most submissions go live immediately.</p>"+"</div></section>"+"<section class='sec cx-form'>"+"<div class='cx-err' hidden></div>"+"<label class='cx-l'>Who is it for"+"<div class='cx-scope'>"+"<button class='cx-opt on' data-cx-fscope='general'>General<span>Any class</span></button>"+"<button class='cx-opt' data-cx-fscope='class'>One class<span>Class-wide</span></button>"+"<button class='cx-opt' data-cx-fscope='spec'>One spec<span>Most specific</span></button>"+"</div>"+"</label>"+"<div class='cx-clsrow' hidden>"+"<label class='cx-l'>Class<select class='cx-f-cls'>"+clsOpts+"</select></label>"+"<label class='cx-l cx-specwrap' hidden>Spec<select class='cx-f-spec'><option value=''>— pick a spec —</option></select></label>"+"</div>"+"<label class='cx-l'>Category<select class='cx-f-cat'>"+catOpts+"</select></label>"+"<label class='cx-l'>Title"+"<input class='cx-f-title' maxlength='80' placeholder='"+
esc(isMacro?"e.g. Mouseover dispel":"e.g. Essence tracker with proc glow")+"' autocomplete='off'></label>"+"<label class='cx-l'>What does it do?"+"<textarea class='cx-f-desc' maxlength='1000' rows='4' placeholder='What it does, when to use it, and anything a new player should know.'></textarea></label>"+"<label class='cx-l'>"+esc(isMacro?"The macro":"The import string")+"<textarea class='cx-f-body' rows='"+(isMacro?"6":"5")+"' spellcheck='false' placeholder='"+
esc(isMacro?"/cast [@mouseover,help] Cleanse":"Paste the !WA:2! string from the WeakAuras export window")+"'></textarea></label>"+
(isMacro?"":"<label class='cx-l'>Wago link <span class='cx-opt-tag'>optional</span>"+"<input class='cx-f-wago' maxlength='200' placeholder='https://wago.io/…' autocomplete='off' spellcheck='false'></label>"+"<p class='cx-hint'>Ascension runs its own WeakAuras fork, so Wago cannot categorise these properly — "+"the string is stored here. Add the link too if you keep one there.</p>")+"<label class='cx-l'>Your name"+"<input class='cx-f-author' maxlength='64' placeholder='Discord handle or character name' autocomplete='off'></label>"+"<label class='cx-chk'><input type='checkbox' class='cx-f-pub' checked> Credit me publicly on this page</label>"+"<input class='cx-hp' tabindex='-1' autocomplete='off' aria-hidden='true'>"+"<p class='cx-priv'>We store what you type here and nothing else — no IP, no email, no cookies. "+"Submissions are mirrored to the maintainers' Discord.</p>"+"<div class='cx-actions'><button class='cx-send'>Submit</button></div>"+"</section>";}
function fetchList(){S.loading=true;S.error="";S.stale=false;paint();var url=API+"/list"+qs({kind:S.kind,scope:S.f.scope,cls:S.f.cls,spec:S.f.spec,category:S.f.category,q:S.f.q,sort:S.f.sort,limit:50});fetch(url).then(function(r){if(!r.ok)throw new Error("http_"+r.status);return r.json();}).then(function(d){S.loading=false;S.items=d.items||[];S.total=d.total||0;paint();}).catch(function(){S.loading=false;var local=applyLocalFilters(snapshotItems());S.items=local;S.total=local.length;S.stale=true;if(!local.length)S.error="Could not reach the library, and nothing is bundled offline yet.";paint();});}
function fetchDetail(id){var known=S.items.filter(function(x){return x.id===id;})[0];if(known&&known.body){S.detail=known;S.detailLoading=false;paint();return;}
S.detailLoading=true;fetch(API+"/item/"+encodeURIComponent(id)).then(function(r){if(!r.ok)throw new Error("http_"+r.status);return r.json();}).then(function(d){S.detailLoading=false;S.detail=d;paint();}).catch(function(){S.detailLoading=false;S.detail=snapshotItems().filter(function(x){return x.id===id;})[0]||null;paint();});}
function paint(){var host=document.getElementById("cx-results");if(host){host.innerHTML=resultsHtml();bindResults();return;}
if(H.render)H.render();}
function doVote(id){var token=voteToken();if(!token){H.toast("Voting needs local storage, which is blocked in this browser.");return;}
var item=S.items.filter(function(x){return x.id===id;})[0]||(S.detail&&S.detail.id===id?S.detail:null);var was=!!S.voted[id];if(item)item.votes=Math.max(0,(item.votes||0)+(was?-1:1));if(was)delete S.voted[id];else S.voted[id]=1;saveVoted();paint();fetch(API+"/vote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:id,token:token})}).then(function(r){if(!r.ok)throw new Error("http_"+r.status);return r.json();}).then(function(d){if(item)item.votes=d.votes;if(d.voted)S.voted[id]=1;else delete S.voted[id];saveVoted();paint();}).catch(function(){if(item)item.votes=Math.max(0,(item.votes||0)+(was?1:-1));if(was)S.voted[id]=1;else delete S.voted[id];saveVoted();paint();H.toast("Could not register that vote.");});}
function doCopy(id){var it=S.items.filter(function(x){return x.id===id;})[0]||(S.detail&&S.detail.id===id?S.detail:null);if(!it)return;var text=it.body||"";if(!text){fetch(API+"/item/"+encodeURIComponent(id)).then(function(r){return r.json();}).then(function(d){copyText(d.body||"");}).catch(function(){H.toast("Could not fetch that.");});return;}
copyText(text);}
function copyText(text){if(!text)return;try{navigator.clipboard.writeText(text).then(function(){H.toast("Copied.");H.trackEvent("community_copy");}).catch(function(){H.toast("Copy failed — select the text and copy manually.");});}catch(e){H.toast("Copy failed — select the text and copy manually.");}}
function submitForm(root){var q=function(s){return root.querySelector(s);};var btn=q(".cx-send");var errBox=q(".cx-err");var show=function(m){errBox.textContent=m;errBox.hidden=false;errBox.scrollIntoView({block:"nearest"});};var scope=root.getAttribute("data-scope")||"general";var cls=scope==="general"?"":(q(".cx-f-cls").value||"");var spec=scope==="spec"?(q(".cx-f-spec").value||""):"";var title=q(".cx-f-title").value.trim();var description=q(".cx-f-desc").value.trim();var body=q(".cx-f-body").value.trim();var author=q(".cx-f-author").value.trim();var wagoEl=q(".cx-f-wago");if(scope!=="general"&&!cls)return show("Pick a class.");if(scope==="spec"&&!spec)return show("Pick a spec.");if(title.length<3)return show("Give it a short title (at least 3 characters).");if(description.length<10)return show("Add a bit more detail (at least 10 characters).");if(!body)return show(S.kind==="macro"?"Paste the macro itself.":"Paste the import string.");if(S.kind==="weakaura"&&body.indexOf("!WA:")!==0){return show("That does not look like a WeakAuras export — it should start with !WA:");}
if(author.length<2)return show("Add your name so we can credit you.");var payload={kind:S.kind,title:title,description:description,author:author,authorPublic:q(".cx-f-pub").checked,scope:scope,cls:cls,spec:spec,category:q(".cx-f-cat").value,body:body,wagoUrl:wagoEl?wagoEl.value.trim():"",elapsedMs:Date.now()-S.submitOpenedAt,hp:root.querySelector(".cx-hp").value};btn.disabled=true;btn.textContent="Submitting…";errBox.hidden=true;var restore=function(){btn.disabled=false;btn.textContent="Submit";};var fallback=" If it keeps failing, post it in the Ascension COA Discord.";fetch(API+"/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}).then(function(r){return r.json().then(function(d){return{status:r.status,d:d};}).catch(function(){return{status:r.status,d:{}};});}).then(function(res){if(res.status===201){H.trackEvent("community_submit");H.track("community_kind",S.kind);if(res.d.status==="published"){H.toast("Published — thanks!");S.f={scope:"",cls:"",spec:"",category:"",q:"",sort:"new"};H.go(S.kind==="macro"?"macros":"weakauras",null);}else{root.innerHTML="<div class='empty'><h2>Submitted — pending review</h2>"+"<p>Thanks! This one needs a quick look from a maintainer before it goes live. "+"That usually means it contains a link, custom code, or wording the filter flagged.</p>"+"<p><button class='cx-inline-link' data-cx-goback>Back to "+esc(PLURAL[S.kind].toLowerCase())+"</button></p></div>";root.querySelectorAll("[data-cx-goback]").forEach(function(b){b.onclick=function(){H.go(S.kind==="macro"?"macros":"weakauras",null);};});}
return;}
restore();if(res.status===409)show("That exact "+(S.kind==="macro"?"macro":"aura")+" has already been submitted.");else if(res.status===429)show("We're rate-limited right now — try again in a minute."+fallback);else if(res.status===413)show("That's too large to submit.");else if(res.status===403)show("That submission was refused.");else if(res.status===503)show("Submissions aren't configured yet."+fallback);else if(res.status===400)show(errorText(res.d.error));else show("Couldn't submit that."+fallback);}).catch(function(){restore();show("Network error — your text is still here, try again."+fallback);});}
function errorText(code){var M={title_too_short:"The title is too short.",title_too_long:"The title is too long.",description_too_short:"Add a bit more detail.",description_too_long:"That description is too long.",author_required:"Add your name so we can credit you.",body_required:"Paste the content itself.",body_too_long:"That's too large to submit.",bad_category:"Pick a category.",bad_wago_url:"That Wago link doesn't look right — it should be https://wago.io/…",class_required:"Pick a class.",spec_required:"Pick a spec.",unknown_class:"That class isn't recognised.",unknown_spec:"That spec isn't recognised.",too_fast:"That was too quick — take a moment and try again.",honeypot:"That submission was refused."};return M[code]||"That didn't validate — check the fields and try again.";}
function openSuggest(id){S.editOpenedAt=Date.now();var it=S.detail&&S.detail.id===id?S.detail:null;if(!it)return;var o=document.createElement("div");o.className="fb-wrap cx-modal";o.innerHTML="<div class='fb-scrim' data-cx-close></div>"+"<div class='fb-box' role='dialog' aria-modal='true' aria-label='Suggest an edit'>"+"<div class='fb-h'><b>Suggest an edit</b><button class='fb-x' data-cx-close aria-label='Close'>&#10005;</button></div>"+"<p class='fb-ctx'>To <b>"+esc(it.title)+"</b></p>"+"<label class='fb-l'>Title<input class='cx-e-title' maxlength='80' value='"+esc(it.title)+"'></label>"+"<label class='fb-l'>Description<textarea class='cx-e-desc' maxlength='1000' rows='4'>"+esc(it.description)+"</textarea></label>"+"<label class='fb-l'>Why does this need changing?<textarea class='cx-e-note' maxlength='500' rows='3' placeholder='e.g. this is filed under the wrong spec, or the macro is missing a line'></textarea></label>"+"<label class='fb-l'>Your name<input class='cx-e-author' maxlength='64' placeholder='Discord handle' autocomplete='off'></label>"+"<input class='cx-hp' tabindex='-1' autocomplete='off' aria-hidden='true'>"+"<p class='fb-priv'>Edits are reviewed before they go live — the entry doesn't change until a maintainer applies it. "+"The content itself can't be replaced here; submit a new one for that.</p>"+"<div class='fb-err' hidden></div>"+"<div class='fb-actions'><button class='fb-send cx-e-send'>Send suggestion</button></div>"+"</div>";document.body.appendChild(o);o.querySelectorAll("[data-cx-close]").forEach(function(b){b.onclick=function(){o.remove();};});o.querySelector(".cx-e-note").focus();o.querySelector(".cx-e-send").onclick=function(){sendSuggest(o,it);};}
function sendSuggest(o,it){var btn=o.querySelector(".cx-e-send");var errBox=o.querySelector(".fb-err");var show=function(m){errBox.textContent=m;errBox.hidden=false;};var title=o.querySelector(".cx-e-title").value.trim();var desc=o.querySelector(".cx-e-desc").value.trim();var note=o.querySelector(".cx-e-note").value.trim();var author=o.querySelector(".cx-e-author").value.trim();if(note.length<10)return show("Say what needs changing (at least 10 characters).");if(author.length<2)return show("Add your name.");var patch={};if(title&&title!==it.title)patch.title=title;if(desc&&desc!==it.description)patch.description=desc;if(!Object.keys(patch).length)return show("Nothing changed — edit the title or description first.");btn.disabled=true;btn.textContent="Sending…";errBox.hidden=true;fetch(API+"/suggest-edit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:it.id,author:author,note:note,patch:patch,elapsedMs:Date.now()-S.editOpenedAt,hp:o.querySelector(".cx-hp").value})}).then(function(r){if(r.status===201){o.remove();H.toast("Thanks — a maintainer will review it.");return;}
btn.disabled=false;btn.textContent="Send suggestion";show(r.status===429?"Rate-limited — try again in a minute.":"Couldn't send that.");}).catch(function(){btn.disabled=false;btn.textContent="Send suggestion";show("Network error — try again.");});}
function bindResults(){var app=document.getElementById("app");if(!app)return;app.querySelectorAll("[data-cx-vote]").forEach(function(b){b.onclick=function(){doVote(b.getAttribute("data-cx-vote"));};});app.querySelectorAll("[data-cx-copy]").forEach(function(b){b.onclick=function(){doCopy(b.getAttribute("data-cx-copy"));};});app.querySelectorAll("[data-cx-open]").forEach(function(a){a.onclick=function(e){if(H.navMod(e))return;e.preventDefault();H.go(S.kind==="macro"?"macros":"weakauras",a.getAttribute("data-cx-open"));};});}
function bind(sub){var app=document.getElementById("app");if(!app)return;app.querySelectorAll("[data-cx-goback]").forEach(function(b){b.onclick=function(){H.go(S.kind==="macro"?"macros":"weakauras",null);};});app.querySelectorAll("[data-cx-gosubmit]").forEach(function(b){b.onclick=function(){H.go(S.kind==="macro"?"macros":"weakauras","submit");};});app.querySelectorAll("[data-cx-suggest]").forEach(function(b){b.onclick=function(){openSuggest(b.getAttribute("data-cx-suggest"));};});if(sub==="submit"){bindSubmit(app);return;}
if(sub){bindResults();return;}
app.querySelectorAll("[data-cx-scope]").forEach(function(b){b.onclick=function(){S.f.scope=b.getAttribute("data-cx-scope");if(S.f.scope==="general"){S.f.cls="";S.f.spec="";}
H.render();fetchList();};});app.querySelectorAll("[data-cx-cat]").forEach(function(b){b.onclick=function(){S.f.category=b.getAttribute("data-cx-cat");H.render();fetchList();};});var clsSel=app.querySelector("[data-cx-cls]");if(clsSel)clsSel.onchange=function(){S.f.cls=clsSel.value;S.f.spec="";H.render();fetchList();};var specSel=app.querySelector("[data-cx-spec]");if(specSel)specSel.onchange=function(){S.f.spec=specSel.value;fetchList();};var sortSel=app.querySelector("[data-cx-sort]");if(sortSel)sortSel.onchange=function(){S.f.sort=sortSel.value;fetchList();};var search=app.querySelector("[data-cx-q]");if(search){search.oninput=function(){if(_searchTimer)clearTimeout(_searchTimer);_searchTimer=setTimeout(function(){S.f.q=search.value.trim();fetchList();},300);};}
bindResults();}
function bindSubmit(app){var root=app.querySelector(".cx-form");if(!root)return;S.submitOpenedAt=Date.now();root.setAttribute("data-scope","general");var clsRow=root.querySelector(".cx-clsrow");var specWrap=root.querySelector(".cx-specwrap");var clsSel=root.querySelector(".cx-f-cls");var specSel=root.querySelector(".cx-f-spec");root.querySelectorAll("[data-cx-fscope]").forEach(function(b){b.onclick=function(){var v=b.getAttribute("data-cx-fscope");root.setAttribute("data-scope",v);root.querySelectorAll("[data-cx-fscope]").forEach(function(x){x.classList.remove("on");});b.classList.add("on");clsRow.hidden=v==="general";specWrap.hidden=v!=="spec";};});clsSel.onchange=function(){specSel.innerHTML="<option value=''>— pick a spec —</option>"+specsOf(clsSel.value).map(function(n){return"<option value='"+esc(n)+"'>"+esc(n)+"</option>";}).join("");};root.querySelector(".cx-send").onclick=function(){submitForm(root);};}
window.ASCC={init:function(host){H=host||{};esc=H.esc||esc;loadVoted();},view:function(view,sub){S.kind=KIND[view]||"macro";if(sub==="submit")return submitView();if(sub){if(!S.detail||S.detail.id!==sub){var seed=S.items.filter(function(x){return x.id===sub;})[0];if(seed&&seed.body){S.detail=seed;S.detailLoading=false;}
else{S.detail=null;S.detailLoading=true;}}
return detailView(sub);}
return browseView();},bind:function(view,sub){S.kind=KIND[view]||"macro";bind(sub);if(sub==="submit")return;if(sub){if(!S.detail||S.detail.id!==sub)fetchDetail(sub);return;}
fetchList();},meta:function(view,sub){var kind=KIND[view]||"macro";var plural=PLURAL[kind];if(sub==="submit"){return{title:"Submit "+(kind==="macro"?"a Macro":"a WeakAura")+" — Conquest of Azeroth",desc:"Share your Conquest of Azeroth "+plural.toLowerCase()+" with the community — pick a class and spec, paste it, get credited."};}
if(sub&&S.detail&&S.detail.id===sub){return{title:S.detail.title+" — Conquest of Azeroth "+LABEL[kind],desc:S.detail.description};}
return{title:"Conquest of Azeroth "+plural,desc:"Player-submitted Conquest of Azeroth "+plural.toLowerCase()+" for every class and spec — browse, copy, and share your own."};}};})();