"""Optional SquidBots module: a live mod-playerbots dashboard, vendored from
github.com/Zyth45/squidbots-dashboard (MIT, see LICENSE in this folder) and
shown as the "Bots" tab, replacing the dashboard's own older bots_stats.py page.

squidbots.py runs as its own small local web server on its own port and the
dashboard shows it in an iframe, exactly like modules/exilesdb does -- it is
only started when the tab is opened, and it reads its own dashboard.json
(regenerated here from dashboard_settings.json every start, so DB creds and
paths stay in one place).

Two local changes from upstream, kept small on purpose so `squidbots.py` and
`static/dashboard.js` stay easy to diff against a future update:
  - squidbots.py: each class in "classes" also carries a "top" list (the top
    ten bots of that class, same shape/cap as the leaderboard).
  - static/dashboard.js: renderClasses() lets you click a class row to open
    that "top" list inline -- the per-class drilldown the previous bots page
    had as tabs.
"""

import atexit
import json
import os
import socket
import subprocess
import sys
import time
import urllib.request

MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
SERVER_SCRIPT = os.path.join(MODULE_DIR, "squidbots.py")
CONFIG_PATH = os.path.join(MODULE_DIR, "dashboard.json")
LOG_PATH = os.path.join(MODULE_DIR, "squidbots.log")
PORT = 8879

_proc = None


def _write_config(settings):
    install = settings["install_dir"]
    client_exe = settings.get("client_exe") or ""
    cfg = {
        "_comment": "Generated by module.py from dashboard_settings.json on each start -- edit that in the main dashboard's Settings page, not here.",
        "port": PORT,
        # Folder holding the client .exe, so the Maps/Settings "game client folder" field can
        # default to the same client the parent dashboard's own Settings page already points at
        # (client_exe), instead of asking the user to browse to it a second time.
        "gameClient": os.path.dirname(client_exe) if client_exe else None,
        "mysqlExe": os.path.join(settings["mysql_dir"], "bin", "mysql.exe"),
        "mysqlArgs": ["-h" + settings["mysql_host"], "-P" + str(settings["mysql_port"]),
                     "-u" + settings["mysql_user"], "-p" + settings["mysql_password"]],
        "databases": {"auth": "acore_auth", "characters": "acore_characters", "world": "acore_world"},
        "worldserverPath": os.path.join(install, "worldserver.exe"),
        "dbcDir": os.path.join(install, "dbc"),
        "configDir": os.path.join(settings["configs_dir"], "modules"),
        "coaLog": os.path.join(install, "CoaBots.log"),
        "chatLog": os.path.join(install, "Chat.log"),
        "lootLog": os.path.join(install, "BotLoot.log"),
        "crashesDir": os.path.join(install, "Crashes"),
        "incidentsLog": os.path.join(MODULE_DIR, "watch.txt"),
        "footer": "",
    }
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)


def _listening(port):
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=0.3):
            return True
    except OSError:
        return False


def _served_port(port):
    try:
        with urllib.request.urlopen(f"http://127.0.0.1:{port}/api/config", timeout=2) as r:
            return r.status == 200
    except Exception:
        return False


def status(settings):
    return {"installed": True, "running": _listening(PORT), "port": PORT}


def start(settings):
    """Start squidbots.py if it isn't already up. Returns status()."""
    global _proc
    _write_config(settings)
    if _listening(PORT) and _served_port(PORT):
        return status(settings)
    log = open(LOG_PATH, "ab")
    exe = os.path.join(MODULE_DIR, "squidbots.exe")
    command = [exe] if os.path.isfile(exe) else [sys.executable, SERVER_SCRIPT]
    _proc = subprocess.Popen(
        command,
        cwd=MODULE_DIR, stdin=subprocess.DEVNULL, stdout=log, stderr=log,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )
    for _ in range(40):
        if _listening(PORT):
            break
        time.sleep(0.25)
    return status(settings)


def stop():
    global _proc
    if _proc and _proc.poll() is None:
        _proc.terminate()
    _proc = None


atexit.register(stop)
